### ISSUE TITLE
Panic: `Unable to load create_debug_utils_messenger_ext` when attempting to compile w/debug profile without Vulkan SDK installed

### ISSUE THREAD

**Issue by eliheuer** [MFEK/glif#229]
I'm trying to open and edit a `.glif` file by running `cargo run R_.glif` on a newly set up Arch Linux PC, but I get the following error: `Unable to load create_debug_utils_messenger_ext`.

![2022-01-01-103905_1920x1080_scrot](https://user-images.githubusercontent.com/5162664/147857903-9bbf91ee-7f3d-414a-8dae-e05e8a6ae336.png)

**Comment by eliheuer** [comment]
I installed the Vulkan SDK using this guide and now get a different error: https://vulkan.lunarg.com/doc/sdk/1.2.198.1/linux/getting_started.html

![2022-01-02-002738_1920x1080_scrot](https://user-images.githubusercontent.com/5162664/147870374-54584b31-4f17-4429-aa4c-fc8e27211ddd.png)

**Comment by eliheuer** [comment]
For what it's worth, the binary works. :-)
![2022-01-02-012948_1920x1080_scrot](https://user-images.githubusercontent.com/5162664/147871808-eaeeb743-a572-4c0c-b137-579d7a8f2802.png)

**Comment by eliheuer** [comment]
This issue should be closed after a small readme update to clarify the Vulkan requirements.

I'll open a new issue for the post-vulkan-setup error.

**Comment by ctrlcctrlv** [comment]
The second error is because MFEKglif does not support being given a UFO file as argument, only .glif / .glifjson files.

The first build error, but still being able to use the binary regardless, I believe is because `ash` tries to use the Vulkan SDK validation layer when compiled in debug mode. I believe you would've been able to compile in release mode just fine without the Vulkan SDK, so am not sure about the wording of your PR.

**Comment by eliheuer** [comment]
Ok, Thanks! I just tested this and `cargo run --release .../A_.glif` works without the Vulkan SDK installed, but `cargo run .../A_.glif` gets the first build error.

**Comment by ctrlcctrlv** [comment]
Reopening to track resolution of MaikKlein/ash#544.

(Sorry to keep reopening your issues @eliheuer, really in future please just let me decide when they should be closed, as my thoughts on their relevance to the project may differ from yours given my different point of view as a maintainer.)

**Comment by ctrlcctrlv** [comment]
Update: the real culprit is not `ash` at all, it's `rafx` via its instantiation by `skulpin`. The tracking issue is now https://github.com/aclysma/rafx/issues/180 and/or https://github.com/MFEK/skulpin.rlib/issues/2.

**Comment by aclysma** [comment]
This might be a big, maybe in this code here:  https://github.com/aclysma/rafx/blob/056d01667cf94481f922b9c7e3c8bdf9542c9355/rafx-api/src/backends/vulkan/internal/instance.rs#L117 

If you have a log with trace enabled I can take a look.

What should happen is it sees that there is no extension and skip enabling it (since in debug mode the setting defaults to “if available”)

**Comment by MarijnS95** [comment]
@aclysma Extension loading itself is not fallible, though it'd be funny if the instance extension is found and enabled but the required function(s) are unavailable.

For reference, [this panicking fallback function](https://github.com/MaikKlein/ash/blob/0ae56a09616da34ee03a0d18702b8493c9e9072a/ash/src/vk/extensions.rs#L9476-L9486) is inserted when `vkGetInstanceProcAddr` returns `None`/`null`.

**Comment by ctrlcctrlv** [comment]
rafx should probably be fixed, but as far as MFEK is concerned https://github.com/MFEK/skulpin.rlib/pull/3 closes this issue. I'm sorry I can't provide a trace, only @eliheuer can.
