### ISSUE TITLE
Shapes Tool - Circle & Oval tools add superfluous points

### ISSUE THREAD

**Issue by eliheuer** [MFEK/glif#235]
My personal expected behavior for a font editor's shapes tool is that the circle and oval tools will create a shape with 4 on-curve points. MFEKglif currently creates 8 on-curve points with both the circle and oval tools.

If this is expected that's fine and I will close the issue, but here is my thinking as to why it should be 4 by default.

- 4 is easier to work on and edit for me
- RoboFont, Glyphs, TruFont & Runebender all create 4 as the default
- a 4 point glyph has a smaller file size than an 8 point one
- As far as I know, any circle or oval shape that can be rendered with 8 on-curve points can be rendered with 4

See the screenshots below, the top one is MFEKglyph at this point, and the bottom one is Spoonbender.

![2022-01-03-185231_1920x1080_scrot](https://user-images.githubusercontent.com/5162664/148004168-3ec65f93-66d4-48d6-a485-c590c5ae64ea.png)

![2022-01-03-190353_1920x1080_scrot](https://user-images.githubusercontent.com/5162664/148004177-1c050d32-43eb-4b3b-854d-d0b9c1cee51a.png)

**Comment by ctrlcctrlv** [comment]
Thank you, good bug report. I knew about the problem but needed a reminder to fix it as I'd just gotten used to it. The reason it happens is a side effect of how the `Shapes` tool, and ultimately how the trait `Outline::outline::skia::FromSkiaPath`, is implemented.

This is the entirety of the function that calculates the Bezier for the circle:

https://github.com/MFEK/glif/blob/53ede2f186fd093c0e6893de1f68fe68584bdc9a/src/tools/shapes.rs#L184-L188

Note `Outline::from_skia_path`, this is calling a trait `impl`, the aforementioned `FromSkiaPath`, defined here:

https://github.com/MFEK/glifparser.rlib/blob/123a7c44913d4902b5a422343fc6d1272ddecead/src/outline/skia/from.rs#L11-L13

Over `Outline`, [it just calls](https://github.com/MFEK/glifparser.rlib/blob/123a7c44913d4902b5a422343fc6d1272ddecead/src/outline/skia/from.rs#L158):
```rust
    Outline::from_skoutline(skp.split_skia_path().conics_to_cubics())
```

The problem is the `ConicsToCubics`. Skia shapes created with `skia::Path` contain conics. Note its comments:

```rust
        // The path could contain conics, so our next task is to resolve conics to quads
```

We call `SkPath::convert_conic_to_quads` and then make the results into two adjoining quads.

But MFEKglif barely works at all in quad mode, so we _do not_ try to give our users quads, we immediately take the two quads and make them cubics [using the private glifparser trait `QuadsToCubics`](https://github.com/MFEK/glifparser.rlib/blob/123a7c44913d4902b5a422343fc6d1272ddecead/src/outline/skia.rs#L19) (should probably be moved to MFEK/math.rlib!).

_Thus_, your four extra points. So, what is solution? I suggest instead of writing a circle generator code yourself, which is not good habit to get into as it increases our code size and we already have many libraries, you use Kurbo, Kurbo `Circle` implements `Shape` so you should be able to quite trivially build a Bezier path.

Note this code in math.rlib:

https://github.com/MFEK/math.rlib/blob/08b002c939f2167e27e724b84e455c4e49855993/src/dash_along_path/mod.rs#L105-L120

(I only took all this time to teach as I hoped you'd solve the problem yourself, but if you do not within like … a long time, I will end up doing it hehe)

**Comment by eliheuer** [comment]
Thanks for the detailed write-up on this!

After looking at it, I assume most of the changes I need to make to close this issue are in `glifparser.rlib` and not `glif`?

However, when I try to build `glif` with `glifparser.rlib` toggled to development mode in `Cargo.toml` I get some errors [described here](https://github.com/MFEK/glif/issues/243) that I haven't figured out how to fix yet.

**Comment by ctrlcctrlv** [comment]
Regarding this issue (and not @eliheuer's query already answered in https://github.com/MFEK/glif/discussions/244#discussioncomment-1926001), I actually have had a change of heart regarding an appropriate solution.

Because ellipses (including circles) cannot be exactly described by cubic Bézier curves, the shapes font editors make called "circles" aren't really true circles. They're what I'm calling _typographic circle-alikes_—not mathematical circles, but convenient for type designers, with a very small distinction between circles and these.

Therefore, neither Kurbo nor Skia will ever produce these. It actually _is_ appropriate to add an ellipse output function to MFEKmath…and I'll do that when I've time if @eliheuer does not first.

**Comment by eliheuer** [comment]
Not sure if you have seen this PR, but the `typographic circle-alikes` is something I helped work on for TruFont: https://github.com/trufont/trufont/pull/527

**Comment by ctrlcctrlv** [comment]
@eliheuer Hey, good news :-)

Another issue generic maths libraries won't care about, but which is vital to type design, is circle _direction_. Only Skia cares, but it is an outlier.

@MatthewBlanchard said he plans to rename `MFEKmath` to `MFEKalgorithms`. Presumably `PolarCoordinates` trait would return to glifparser in that case, as it uses no MFEKmath primitives. `TypoCircle` actually should be a trait object, to be implemented in glifparser on `Contour`.

So:

```rust
/// Create a path that's similar to a circle, but not quite one. Has less points and is therefore convenient for type designers.
pub trait TypoCircle {
    /// If the radius is negative, output will have counter-clockwise points.
    fn typo_circle(radius: f64) -> Self;
}

impl<PD: PointData> TypoCircle on Contour<PD> {
    …
}

impl<PD: PointData> TypoCircle on Outline<PD> {
    fn typo_circle(radius: f32) -> Self {
        vec![Contour::typo_circle(radius)]
    }
}

#[cfg(features = "mfek")]
impl<PD: PointData> TypoCircle on MFEKContour<PD> {
    …
}

#[cfg(features = "mfek")]
impl<PD: PointData> TypoCircle on MFEKOutline<PD> {
    fn typo_circle(radius: f32) -> Self {
        vec![MFEKContour::typo_circle(radius)]
    }
}
```

@eliheuer The right file would be `src/outline/create/typo_circle.rs`. Remember to put this in `create.rs` above:

```rust
mod typo_circle;
pub use typo_circle::TypoCircle;
```

**Comment by ctrlcctrlv** [comment]
Oh, you actually might want to call it `typo_ellipse::TypoEllipse`, and then make `TypoCircle` a trait with a guaranteed impl, as such:

```
/// Create a path that's similar to an ellipse, but not quite one. Has less points and is therefore convenient for type designers.
pub trait TypoCircle: TypoEllipse {
    /// If the radius is negative, output will have counter-clockwise points.
    fn typo_circle(radius_x: f32, radius_y: f32);
}

/// Create a path that's similar to a circle, but not quite one. Has less points and is therefore convenient for type designers.
pub trait TypoCircle: TypoEllipse {
    /// If the radius is negative, output will have counter-clockwise points.
    fn typo_circle(radius: f32) -> Self {
        Self::typo_ellipse(radius, radius)
    }
}
```

**Comment by ctrlcctrlv** [comment]
TruFont is cool, I have no real issue with it other than it's too centralized. The unfortunate decision was made to combine everything—font overview, OpenType editor, glyph editor—into one large program, which I believe to be a fatal flaw of modern FOSS font editors which dooms them to always be playing second fiddle to FontForge rather than be innovating in a way that is harmonious with FontForge and allows both projects to be used to work on the same font.

**Comment by ctrlcctrlv** [comment]
TruFont represents four programs in one in MFEK's view, maybe more…MFEKglif, MFEKufo, MFEKopentype, MFEKmetadata…and these programs shouldn't be combined because it causes vendor lock-in to the font editor.
